### ISSUE TITLE
one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by dongfengxijian** [PkuRainBow/OCNet.pytorch#41]
I use your ASP-OC block in my network, but get this error. Can you help me？

**Comment by dongfengxijian** [comment]
`Traceback (most recent call last):
  File "train_test.py", line 482, in <module>
    train()
  File "train_test.py", line 353, in train
    loss.backward()
  File "/home/phd/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/phd/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
`
